# GET ROUTES

get_projects_v1:
  path: /{org}/projects
  defaults: { _controller: App\Controller\ApiControllers\V1\ProjectController::getProjects }
  methods: [ GET, OPTIONS ]

get_project_v1:
  path: /{org}/{project}/project
  defaults: { _controller: App\Controller\ApiControllers\V1\ProjectController::getProject }
  methods: [ GET, OPTIONS ]

get_project_users_v1:
  path: /{org}/{project}/users
  defaults: { _controller: App\Controller\ApiControllers\V1\ProjectController::getProjectUsers }
  methods: [ GET, OPTIONS ]

# POST ROUTES

issue_create_v1:
  path: /{org}/{project}/issue/create
  defaults: { _controller: App\Controller\ApiControllers\V1\IssueController::createIssue }
  methods: [ POST, OPTIONS ]


# PUT ROUTES

issue_move_v1:
  path: /{org}/{project}/issue/move
  defaults: { _controller: App\Controller\ApiControllers\V1\IssueController::moveIssue }
  methods: [ PUT, OPTIONS ]


issue_update_v1:
  path: /{org}/{project}/issue/update
  defaults: { _controller: App\Controller\ApiControllers\V1\IssueController::updateIssue }
  methods: [ PUT, OPTIONS ]