/*

    Vuex mutations

 */
export default {

    SAVE_TOKEN: 'SAVE_TOKEN',
    SAVE_PROJECT: 'SAVE_PROJECT',
    SAVE_PROJECTS: 'SAVE_PROJECTS',
    SAVE_CREATED_ISSUE: 'SAVE_CREATED_ISSUE',
    SAVE_PROJECT_USERS: 'SAVE_PROJECT_USERS',

    GET_PROJECT: 'GET_PROJECT',
    GET_PROJECTS: 'GET_PROJECTS',
    GET_PROJECT_USERS: 'GET_PROJECT_USERS'

}